name: testCommitPushFailure
description: ''
version: 0.0.1
author: kiranadmin@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: testcommitpushfailure
  parentArtefactID: kiranadminprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2023-11-28 06:29:10'
pipelines:
  pipelines/p1:
    name: p1
    description: ''
    author: kiranadmin@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-11-28 06:29:10'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
functions:
  author: null
  createdAt: '2023-11-28 06:29:10'
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.0.5
    isDefault: true
    author: null
    createdAt: '2023-11-28 06:28:55'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.2
    isDefault: true
    author: null
    createdAt: '2023-11-28 06:28:55'
pipelineConfigurations: {}
